### ISSUE TITLE
Error with custom files

### ISSUE THREAD

**Issue by samcro1967** [crazy-max/docker-unbound#12]
#### Steps to reproduce this issue

1.  Create config folder on docker host
2.  docker-compose -d up
3.  docker cp unbound:/etc/unbound/unbound.conf . (to config folder)
4.  docker restart unbound

#### Expected behaviour
ubound should start with custom unbound.conf

#### Actual behaviour
unbound fails to start

### Configuration

* Docker version (type `docker --version`) : 20:10:14
* Docker compose version if applicable (type `docker-compose --version`) :  1.29.1
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.04
* System info (type `uname -a`) :  Linux localserver 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker-compose
```
  unbound:
    hostname: unbound
    image: crazymax/unbound
    container_name: unbound
    restart: always
    volumes:
      - "${docker}/unbound/config:/config:ro"
    ports:
      - 5053:5053/tcp
      - 5053:5053/udp
    user: 1000:1000
```
### Docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 96
  Running: 94
  Paused: 0
  Stopped: 2
 Images: 100
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-39-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.12GiB
 Name: localserver
 ID: TJE6:MOTK:7QFB:G52G:LXBZ:GLLL:4YWV:ZXPR:ASEF:4H5O:Z3DZ:67G2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: user1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  osu.registry:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs
```
/config/unbound.conf:1: error: too many include files
/config/unbound.conf:32: error: too many include files
/config/unbound.conf:32: error: too many include files
read /etc/unbound/unbound.conf failed: 3 errors in configuration file
[1649184966] unbound[1:0] fatal error: Could not read config file: /etc/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
```

**Comment by agneevX** [comment]
> ```
> /config/unbound.conf:1: error: too many include files
> /config/unbound.conf:32: error: too many include files
> /config/unbound.conf:32: error: too many include files
> ```

Can you share your configuration file(s)?

**Comment by samcro1967** [comment]
Here they are.
[config.zip](https://github.com/crazy-max/docker-unbound/files/8451480/config.zip)

**Comment by agneevX** [comment]
>  include: "/config/*.conf"

I see what the issue is; it's referencing itself.

You could change it to `include: "/config/forward-records.conf"`, since you have just a single other file.

On a related note, this image bundles an [`unbound.conf`](https://github.com/crazy-max/docker-unbound/blob/master/rootfs/etc/unbound/unbound.conf), that's used as the default file.

Your files include a lot of the underlying config... I'm not quite sure how unbound handles duplicate lines, but it's worth checking out.

Personally, I use a single unbound.conf and bind mount that.

```yml
  unbound:
    container_name: unbound
    image: crazymax/unbound
    restart: unless-stopped
    healthcheck:
      test: "if $$(wget -q --spider -T 3 https://1.1.1.1); then drill -Q -p 5053 $$(echo $$RANDOM | md5sum | head -c 20; echo).test.dnsleaktest.com > /dev/null; else exit 0; fi"
    depends_on:
      - adguard-home
    networks:
      dns: {}
    ports:
      - 127.0.0.1:5053:5053/udp
      - 127.0.0.1:5053:5053/tcp
    tmpfs:
      - /config:size=1m
    volumes:
      - /opt/appdata/unbound/unbound.conf:/etc/unbound/unbound.conf
    labels:
      traefik.enable: false
```
