### ISSUE TITLE
Cannot replace unbound.conf 

### ISSUE THREAD

**Issue by aqtoo** [crazy-max/docker-unbound#57]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-unbound/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When attempting to replace the unbound.conf with my own, I get the error 
`[1734038702] unbound-checkconf[7:0] fatal error: server-key-file: "/var/run/unbound/unbound_server.key" does not exist
/var/run/unbound/unbound_server.key: No such file or directory`

I am baffled as I don't touch that directory within my volumes, only doing.

`     - "./config/unbound/unbound.conf:/etc/unbound/unbound.conf:ro"`

I am a newbie at this but perhaps someone can help?

I understand this is a configuration issue on my end, somewhere.

### Expected behaviour

The configuration to work as expected.
[unbound.zip](https://github.com/user-attachments/files/18117703/unbound.zip)
(A slightly altered version from https://github.com/ar51an/unbound-redis trying to incorporate what's needed)

### Actual behaviour

As stated above, it just errors acting as if those directories don't exist.

### Steps to reproduce

N/A

### Docker info

```text
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 18
  Running: 17
  Paused: 0
  Stopped: 1
 Images: 33
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.31-v8.1.el9.altarch
 Operating System: Rocky Linux 9.5 (Blue Onyx)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.629GiB
 Name: ark
 ID: 1750dc80-21e7-421d-a0e0-93ad45f748f5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
[rocky@ark pihole]$
```

### Docker Compose config

```yaml
`  unbound:
    container_name: unbound
    depends_on:
      redis:
        condition: service_started
        required: true
    image: crazymax/unbound
    networks:
      pihole-unbound: null
    ports:
      - mode: ingress
        target: 5053
        published: "5053"
        protocol: tcp
      - mode: ingress
        target: 5053
        published: "5053"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /opt/docker/pihole/config/unbound/extras
        target: /config
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /opt/docker/pihole/config/unbound/unbound.conf
        target: /etc/unbound/unbound.conf
        read_only: true
        bind:
          create_host_path: true`
```

### Logs

```text
N/A
```

### Additional info

I apologise if my words are unclear, I can try to be more concise if asked direct questions.
